### ISSUE TITLE
SQL Database Construction

### ISSUE THREAD

**Issue by ArunRetnakumar** [A6h9lash/MSC-group-project#13]
Places to discuss and post updates on SQL Database Construction and Schema

**Comment by Tong186** [comment]
Hey, I found a good tutorial to insert data from CSV file into an SQLite database using Python.
Here is the link, hopefully, it will be useful.

https://medium.com/swlh/how-to-insert-data-from-csv-file-into-a-sqlite-database-using-python-82f7d447866a

**Comment by ArunRetnakumar** [comment]
https://www.blog.pythonlibrary.org/2017/12/12/flask-101-adding-a-database/ <- this is a good link explaining the steps on how to construct the database for Flask integration.

https://leportella.com/english/2019/01/10/sqlalchemy-basics-tutorial.html <- this link does a good job explaining how each of the steps actually work/what they do.

**Comment by ArunRetnakumar** [comment]
https://www.lucidchart.com/pages/database-diagram/database-design#discovery__top <- site for Database design
